# This docker-compose is intended for end-users, developers should use the
# docker-compose under the docker/ folder.
services:
  transmute:
    image: ghcr.io/transmute-app/transmute:main
    container_name: transmute
    restart: unless-stopped
    ports:
        - 3313:3313
    volumes:
      - transmute_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3319/api/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  transmute_data: